language: cpp

compiler:
  - clang
  - gcc

env:
  - OMP_NUM_THREADS=4
    IQTREE_FLAGS="omp"
  - OMP_NUM_THREADS=4
    IQTREE_FLAGS="mpi"
  - OMP_NUM_THREADS=4
    IQTREE_FLAGS="omp mpi"

# disable the default submodule logic
git:
  submodules: false

# use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
  - sed -i 's|git@git.assembla.com:|git://git.assembla.com/|' .gitmodules
  - git submodule update --init --recursive

install:
  - mkdir build && cd build && cmake -DIQTREE_FLAGS="$IQTREE_FLAGS" .. && make && make install
