language: cpp

# https://jonasw.de/blog/2015/07/22/develop/cplusplus14-on-travis-with-cmake/
#addons:
#  apt:
#    sources:
#      - llvm-toolchain-precise
#      - ubuntu-toolchain-r-test
#    packages:
#      - clang-3.7
#      - g++-5
#      - gcc-5

addons:
  apt:
    packages:
      # CMake 2.8.10 or higher is required.  You are running version 2.8.7
      - cmake

compiler:
  - clang
  - gcc

env:
  - OMP_NUM_THREADS=4
    IQTREE_FLAGS="omp"
  - OMP_NUM_THREADS=4
    IQTREE_FLAGS="mpi"
  - OMP_NUM_THREADS=4
    IQTREE_FLAGS="omp mpi"

# disable the default submodule logic
# https://gist.github.com/petrbel/c3bf7e0f59c22a52f534
git:
  submodules: false

# use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
  - sed -i 's|git@git.assembla.com:|git://git.assembla.com/|' .gitmodules
  - git submodule update --init --recursive

install:
  - mkdir build && cd build && cmake -DIQTREE_FLAGS="$IQTREE_FLAGS" .. && make && make install
