language: cpp

# https://jonasw.de/blog/2015/07/22/develop/cplusplus14-on-travis-with-cmake/
#addons:
#  apt:
#    sources:
#      - llvm-toolchain-precise
#      - ubuntu-toolchain-r-test
#    packages:
#      - clang-3.7
#      - g++-5
#      - gcc-5

addons:
  apt:
    sources:
      # https://launchpad.net/~george-edison55/+archive/ubuntu/precise-backports
      # cmake 3.2.3-5ppa5~precise1
      # The following packages have unmet dependencies:
      # cmake : Depends: cmake-data (= 3.2.3-5ppa5~precise1) but 2.8.7-0ubuntu5 is to be installed
      # E: Unable to correct problems, you have held broken packages.
      #- george-edison55-precise-backports
      # https://launchpad.net/~kalakris/+archive/ubuntu/cmake
      # cmake 2.8.11.2-1ubuntu2~precise1
      - kalakris-cmake
    packages:
      # CMake 2.8.10 or higher is required.  You are running version 2.8.7
      - cmake

compiler:
  - clang
  - gcc

env:
  - OMP_NUM_THREADS=4
    IQTREE_FLAGS="omp"
  - OMP_NUM_THREADS=4
    IQTREE_FLAGS="mpi"
  - OMP_NUM_THREADS=4
    IQTREE_FLAGS="omp mpi"

# disable the default submodule logic
# https://gist.github.com/petrbel/c3bf7e0f59c22a52f534
git:
  submodules: false

# use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
  - echo $PATH
  - exit 1
  - sed -i 's|git@git.assembla.com:|git://git.assembla.com/|' .gitmodules
  - git submodule update --init --recursive

install:
  - mkdir build && cd build && cmake -DIQTREE_FLAGS="$IQTREE_FLAGS" -DCMAKE_INSTALL_PREFIX:PATH=$HOME/bin .. && make -j$(nproc) && make install
