language: cpp

compiler:
  - clang
  - gcc

env:
  - OMP_NUM_THREADS=4

# disable the default submodule logic
git:
  submodules: false

before_install:
  #- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - sed -i 's|git@assembla.com:|git://git@assembla.com/|' .gitmodules
  - git submodule update --init --recursive
